framework:
    notifier:
        chatter_transports:
            fakechat: '%env(FAKE_CHAT_DSN)%'
        texter_transports:
        channel_policy:
            # use chat/slack, chat/telegram, sms/twilio or sms/nexmo
            urgent: ['email']
            high: ['email']
            medium: ['email']
            low: ['email']
        admin_recipients:
            - { email: "%env(string:default:app.default_admin_email:ADMIN_EMAIL)%" }
