name: symfony-the-fast-track-63

services:
  app:
    image: the-fast-track/app
    command: symfony server:start --no-tls
    volumes:
      - ./:/var/www/html
    depends_on:
      database:
        condition: service_started
      message-broker:
        condition: service_healthy

  app-consumer:
    image: the-fast-track/app-consumer
    command: symfony console messenger:consume async -vv
    volumes:
      - ./:/var/www/html
    depends_on:
      database:
        condition: service_started
      message-broker:
        condition: service_healthy

  message-broker:
    hostname: rabbit
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_VHOST: rabbit
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-guest}
    volumes:
      - message-broker_data:/var/lib/rabbitmq

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    image: schickling/mailcatcher
###< symfony/mailer ###

volumes:
  message-broker_data:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
