version: '3'

services:
  app:
    build:
      context: .docker/php
      args:
        PHP_TYPE: fpm
    ports:
      - '80:8000'

  app-consumer:
    build:
      context: .docker/php
      args:
        PHP_TYPE: cli

  message-broker:
    ports:
      - '5672:5672'
      - '1081:15672'

###> doctrine/doctrine-bundle ###
  database:
    ports:
      - '5432:5432'
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    ports: ["1025", "1080"]
###< symfony/mailer ###
