version: '3'

services:
  app:
    build: .docker/php
    ports:
      - '80:8000'

###> doctrine/doctrine-bundle ###
  database:
    ports:
      - '5432:5432'
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    ports: ["1025", "1080"]
###< symfony/mailer ###
